package com.demo.commons.properties.restclient;

import com.demo.commons.tracing.enums.AutoGeneratedParam;
import com.demo.commons.tracing.enums.TraceParam;
import lombok.Getter;
import lombok.Setter;

import java.util.Map;
import java.util.TreeMap;

@Getter
@Setter
public class HeaderTemplate {

  private Map<String, String> provided = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
  private Map<String, String> forwarded = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
  private Map<String, AutoGeneratedParam> autoGenerated = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
  private Map<String, TraceParam> tracing = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);

}